spring:
  application:
    name: backend-client
  cloud:
    bus:
      enabled: false
    discovery:
      enabled: false
    consul:
      enabled: false
      config:
        enabled: false
backend-server-v1:
  ribbon:
    listOfServers:  localhost:9022
proxy:
  to: backend-server-v1
