spring:
  application:
    name: backend-client
  cloud:
    bus:
      enabled: false
    discovery:
      enabled: false
    consul:
      enabled: false
      config:
        enabled: false
proxy:
  to: backend-server
