spring:
  application:
    name: ${SERVICE_NAME}
  cloud:
    consul:
      host: ${CONSUL_SERVER}
      port: 8500
zuul:
  ignoreLocalService: false
  routes:
    backend-server:
      path: /api/home
      serviceId:  backend-server
