server:
  port: 8003
spring:
  application:
    name: zuul-gateway
ribbon:
  eureka:
    enabled:  false
zuul:
  ignoreLocalService: false
  routes:
    backendClient:
      path: /api/home
      serviceId:  backend-client
