spring:
  application:
    name: zuul
  cloud:
    consul:
      enabled:  false
security:
  sessions: ALWAYS
  oauth2:
    client:
      clientId: JQWRKHm3QM
      clientSecret: qajJmYbPV2hTWXRASjje
      accessTokenUri: https://test.appdirect.com/oauth/token
      userAuthorizationUri: https://test.appdirect.com/oauth/authorize
    resource:
      preferTokenInfo:  false
      userInfoUri: https://test.appdirect.com/oauth/openid/userinfo
configuration-test: Hello there!
