spring:
  cloud:
    consul:
      host: localhost
      port: 8500
zuul:
  ignoreLocalService: false
  routes:
    backend-server:
      path: /api/home
      serviceId:  backend-server
backend-server:
  ribbon:
    listOfServers:  localhost:9023
