spring:
  application:
    name: ${SERVICE_NAME}
  cloud:
    consul:
      host: ${CONSUL_SERVER}
      port: 8500
zuul:
  ignoreLocalService: false
  ignore-services:  *
  routes:
    pdf-html:
      path: /pdf
      serviceId:  pdf-html
    pdf-service:
      path: /pdf-service
      serviceId:  pdf-service-8888
    pdf-generator:
      path: /pdf-generator
      serviceId:  pdf-generator
    
